server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/voucher
    username: voucher_admin
    password: 123456
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop