server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/voucher
    username: voucher_admin
    password: 123456
  jpa:
    show-sql: false
#    generate-ddl: true
    hibernate:
      ddl-auto: validate
#    sql:
#      init:
#        mode: always
  liquibase:
    enabled: false  # Disable Liquibase by default
    change-log: db/changelog/changelog-master.xml
    user: voucher_admin
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: "*"

springfox:
  documentation:
    swagger:
      v2:
        path: /vouchermaker/swagger.json

app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration-milliseconds: 604800000
