spring:
  datasource:
    url: jdbc:h2:mem:vouchers
    driverClassName: org.h2.Driver
    username: admin
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      sql:
        init:
          mode: always
  h2:
    console:
      enabled: true

  liquibase:
    change-log: db/changelog/test-changelog-master.xml
    user: admin
    password: 1234